spring.application.name=modulo-automatizado

spring.datasource.url=jdbc:postgresql://localhost:5432/modulo_automatizado
spring.datasource.username=modulo_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#app.simulation-data.enabled=${SIMULATION_DATA_ENABLED:false}
app.simulation-data.enabled=false
app.reservation-data.enabled=false
app.validation-reservation-data.enabled=false
app.test-base-data.enabled=false
app.integration-reservation-data.enabled=false

# Correo electrónico
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.enabled=${MAIL_ENABLED:false}
app.mail.from=${MAIL_FROM:}
app.mail.override-to=${MAIL_OVERRIDE_TO:}