spring.application.name=modulo-automatizado

spring.datasource.url=jdbc:postgresql://localhost:5432/modulo_automatizado
spring.datasource.username=modulo_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#app.simulation-data.enabled=${SIMULATION_DATA_ENABLED:false}
app.simulation-data.enabled=false
app.reservation-data.enabled=false
app.validation-reservation-data.enabled=false
app.test-base-data.enabled=false
app.integration-reservation-data.enabled=false